name: 'Publish schema to GraphQL Hive'
description: 'Publishes a schema to GraphQL Hive schema repository'
author: 'Open Formation GmbH'
inputs:
  service-name:
    required: true
    description: 'Name of the service in Hive'
  service-url:
    required: true
    description: 'URL of the service endpoint'
  schema-path:
    required: true
    description: 'Path to the .graphql schema file'
  hive-registry-access-token:
    required: true
    description: 'Hive registry access token'
runs:
  using: 'node16'
  main: 'dist/index.js'
